name: Doit
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  data_plugin:
    path: plugins/data_plugin

  cupertino_icons: ^0.1.2
#  data_plugin: ^0.0.12
  #Toast通知
  fluttertoast: ^2.1.1
  shared_preferences: ^0.5.1+1
  #图片缓存
  cached_network_image: ^1.1.0
  path_provider: ^1.1.2
  #SQLite数据库
  sqflite: ^1.1.6
  #Sliver悬浮按钮
  sliver_fab: ^1.0.0
  #日期选择器
  flutter_cupertino_date_picker: ^1.0.8
  #屏幕适配
  #flutter_screenutil: ^0.5.3
  #setting page
  flutter_cupertino_settings: ^0.1.0
  #Icon
  font_awesome_flutter: ^8.5.0
  #屏幕适配
  auto_size:
    git:
      url: git://github.com/flutterchina/auto_size.git



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/user.png
    - images/login_bg.png
    - images/do_it.png
    - images/img_0.png
    - images/img_1.png
    - images/img_2.png
    - images/app_icon.png
    - images/clockbg_0.png



